-- A column belongs to at most one group in its own course and gradebook.
ALTER TABLE public.gradebooks ADD CONSTRAINT gradebooks_id_class_unique UNIQUE (id, class_id);

CREATE TABLE public.gradebook_column_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gradebook_id bigint NOT NULL,
    class_id bigint NOT NULL,
    name text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, gradebook_id, class_id),
    FOREIGN KEY (gradebook_id, class_id) REFERENCES public.gradebooks (id, class_id) ON DELETE CASCADE
);
CREATE INDEX ON public.gradebook_column_groups (gradebook_id);
ALTER TABLE public.gradebook_column_groups ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.gradebook_column_groups TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.gradebook_column_groups_id_seq TO authenticated, service_role;


ALTER TABLE public.gradebook_columns ADD COLUMN group_id bigint;
ALTER TABLE public.gradebook_columns ADD CONSTRAINT gradebook_columns_group_fk
    FOREIGN KEY (group_id, gradebook_id, class_id)
    REFERENCES public.gradebook_column_groups (id, gradebook_id, class_id)
    ON DELETE SET NULL (group_id);
CREATE INDEX ON public.gradebook_columns (group_id);

CREATE POLICY "class members read groups" ON public.gradebook_column_groups
    FOR SELECT TO authenticated USING (
        public.authorizeforclassgrader(class_id)
        OR (public.authorizeforclass(class_id) AND EXISTS (
            SELECT 1 FROM public.gradebook_columns c WHERE c.group_id = gradebook_column_groups.id
        ))
    );
CREATE POLICY "instructors manage groups" ON public.gradebook_column_groups
    FOR ALL TO authenticated USING (public.authorizeforclassinstructor(class_id))
    WITH CHECK (public.authorizeforclassinstructor(class_id));


-- Import legacy layout once. Reused by the local seeder, which creates its
-- legacy fixtures after migrations run. Never overwrite persisted membership.
CREATE FUNCTION public.initialize_gradebook_column_groups(target_gradebook_id bigint)
RETURNS void LANGUAGE plpgsql SET search_path = '' AS $$
DECLARE
    col record;
    prefix text;
    previous_prefix text := '';
    previous_order integer := -1;
    current_group bigint;
    label text;
BEGIN
    PERFORM 1 FROM public.gradebooks WHERE id = target_gradebook_id FOR UPDATE;
    IF EXISTS (SELECT 1 FROM public.gradebook_column_groups WHERE gradebook_id = target_gradebook_id) THEN
        RETURN;
    END IF;
    FOR col IN SELECT * FROM public.gradebook_columns WHERE gradebook_id = target_gradebook_id
        ORDER BY coalesce(sort_order, 0), id
    LOOP
        prefix := coalesce(nullif(split_part(col.slug, '-', 1), ''), 'other');
        IF prefix = 'assignment' AND array_length(string_to_array(col.slug, '-'), 1) >= 3 THEN
            prefix := 'assignment-' || split_part(col.slug, '-', 2);
        END IF;
        IF current_group IS NULL OR prefix <> previous_prefix
            OR (previous_order <> -1 AND coalesce(col.sort_order, 0) <> previous_order + 1) THEN
            label := CASE WHEN prefix LIKE 'assignment-%' THEN split_part(prefix, '-', 2) ELSE prefix END;
            -- An empty assignment subtype had a blank legacy header.
            label := upper(left(label, 1)) || substr(label, 2);
            INSERT INTO public.gradebook_column_groups (gradebook_id, class_id, name)
                VALUES (col.gradebook_id, col.class_id, label) RETURNING id INTO current_group;
        END IF;
        UPDATE public.gradebook_columns SET group_id = current_group WHERE id = col.id;
        previous_prefix := prefix;
        previous_order := coalesce(col.sort_order, 0);
    END LOOP;
END;
$$;
REVOKE ALL ON FUNCTION public.initialize_gradebook_column_groups(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.initialize_gradebook_column_groups(bigint) TO service_role;

SELECT public.initialize_gradebook_column_groups(id) FROM public.gradebooks ORDER BY id;

CREATE TRIGGER set_updated_at_on_gradebook_column_groups
    BEFORE UPDATE ON public.gradebook_column_groups
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER broadcast_gradebook_column_groups
    AFTER INSERT OR UPDATE OR DELETE ON public.gradebook_column_groups
    FOR EACH ROW EXECUTE FUNCTION public.broadcast_course_table_change_unified();
