-- A column belongs to at most one group in its own course and gradebook.
ALTER TABLE public.gradebooks ADD CONSTRAINT gradebooks_id_class_unique UNIQUE (id, class_id);

CREATE TABLE public.gradebook_column_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gradebook_id bigint NOT NULL,
    class_id bigint NOT NULL,
    name text NOT NULL CHECK (length(btrim(name)) > 0),
    sort_order integer NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, gradebook_id, class_id),
    FOREIGN KEY (gradebook_id, class_id) REFERENCES public.gradebooks (id, class_id) ON DELETE CASCADE
);
CREATE INDEX ON public.gradebook_column_groups (gradebook_id);
ALTER TABLE public.gradebook_column_groups ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.gradebook_column_groups TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.gradebook_column_groups_id_seq TO authenticated, service_role;


ALTER TABLE public.gradebook_columns ADD COLUMN group_id bigint;
ALTER TABLE public.gradebook_columns ADD CONSTRAINT gradebook_columns_group_fk
    FOREIGN KEY (group_id, gradebook_id, class_id)
    REFERENCES public.gradebook_column_groups (id, gradebook_id, class_id)
    ON DELETE SET NULL (group_id);
CREATE INDEX ON public.gradebook_columns (group_id);

CREATE POLICY "class members read groups" ON public.gradebook_column_groups
    FOR SELECT TO authenticated USING (
        public.authorizeforclassgrader(class_id)
        OR (public.authorizeforclass(class_id) AND EXISTS (
            SELECT 1 FROM public.gradebook_columns c WHERE c.group_id = gradebook_column_groups.id
        ))
    );
CREATE POLICY "instructors manage groups" ON public.gradebook_column_groups
    FOR ALL TO authenticated USING (public.authorizeforclassinstructor(class_id))
    WITH CHECK (public.authorizeforclassinstructor(class_id));


-- Import legacy layout once. Reused by the local seeder, which creates its
-- legacy fixtures after migrations run. Never overwrite persisted membership.
CREATE FUNCTION public.initialize_gradebook_column_groups(target_gradebook_id bigint)
RETURNS void LANGUAGE plpgsql SET search_path = '' AS $$
DECLARE
    family record;
    current_group bigint;
BEGIN
    PERFORM 1 FROM public.gradebooks WHERE id = target_gradebook_id FOR UPDATE;
    IF EXISTS (SELECT 1 FROM public.gradebook_column_groups WHERE gradebook_id = target_gradebook_id) THEN
        RETURN;
    END IF;
    -- Numeric suffixes identify attempts, not the words inside a family name.
    -- Gaps and interleaving do not split a family. Ambiguous slugs stay separate.
    FOR family IN
        WITH classified AS (
            SELECT c.*, CASE
                WHEN slug ~ '^assignment-[a-z]+(-[0-9]+)?$'
                    THEN regexp_replace(substr(slug, 12), '-[0-9]+$', '')
                WHEN slug ~ '^[a-z]+(-[a-z]+)*-[0-9]+$'
                    THEN regexp_replace(slug, '-[0-9]+$', '')
                ELSE 'column:' || id::text
            END AS family_key
            FROM public.gradebook_columns c WHERE gradebook_id = target_gradebook_id
        )
        SELECT family_key, min(class_id) AS class_id, array_agg(id) AS column_ids,
            min(coalesce(sort_order, 0)) AS first_order, min(id) AS first_id,
            CASE WHEN family_key LIKE 'column:%' THEN min(name)
                ELSE replace(initcap(replace(family_key, '-', ' ')), 'Ai ', 'AI ')
            END AS label
        FROM classified GROUP BY family_key
        ORDER BY first_order, first_id
    LOOP
        INSERT INTO public.gradebook_column_groups (gradebook_id, class_id, name, sort_order)
            VALUES (target_gradebook_id, family.class_id, coalesce(nullif(btrim(family.label), ''), 'Untitled'),
                family.first_order) RETURNING id INTO current_group;
        UPDATE public.gradebook_columns SET group_id = current_group WHERE id = ANY(family.column_ids);
    END LOOP;
END;
$$;
REVOKE ALL ON FUNCTION public.initialize_gradebook_column_groups(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.initialize_gradebook_column_groups(bigint) TO service_role;

SELECT public.initialize_gradebook_column_groups(id) FROM public.gradebooks ORDER BY id;

CREATE TRIGGER set_updated_at_on_gradebook_column_groups
    BEFORE UPDATE ON public.gradebook_column_groups
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER broadcast_gradebook_column_groups
    AFTER INSERT OR UPDATE OR DELETE ON public.gradebook_column_groups
    FOR EACH ROW EXECUTE FUNCTION public.broadcast_course_table_change_unified();

-- Group order is independent of column order and never rewrites membership.
CREATE FUNCTION public.gradebook_column_groups_reorder(p_gradebook_id bigint, p_group_ids bigint[])
RETURNS void LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$
DECLARE
    course_id bigint;
    expected bigint[];
BEGIN
    SELECT class_id INTO course_id FROM public.gradebooks WHERE id = p_gradebook_id;
    IF auth.uid() IS NULL OR NOT coalesce(public.authorizeforclassinstructor(course_id), false) THEN
        RAISE EXCEPTION 'Instructor access required' USING ERRCODE = '42501';
    END IF;
    PERFORM pg_catalog.pg_advisory_xact_lock(p_gradebook_id);
    SELECT coalesce(array_agg(id ORDER BY id), '{}'::bigint[]) INTO expected
        FROM public.gradebook_column_groups WHERE gradebook_id = p_gradebook_id;
    IF p_group_ids IS NULL OR expected IS DISTINCT FROM
        ARRAY(SELECT unnest(p_group_ids) ORDER BY 1) THEN
        RAISE EXCEPTION 'Supply every group exactly once; refresh after concurrent changes';
    END IF;
    UPDATE public.gradebook_column_groups g SET sort_order = ord.position - 1
        FROM unnest(p_group_ids) WITH ORDINALITY AS ord(id, position)
        WHERE g.id = ord.id AND g.gradebook_id = p_gradebook_id;
END;
$$;
REVOKE ALL ON FUNCTION public.gradebook_column_groups_reorder(bigint, bigint[]) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.gradebook_column_groups_reorder(bigint, bigint[]) TO authenticated;
